### ISSUE TITLE
NullPointer in InputFieldView

### ISSUE THREAD

**Issue by mikkoville** [verygoodsecurity/vgs-collect-android#193]
**Describe the bug**
We are seeing crash reports with vgs collect `InputFieldView`

Here is the stack trace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewRootImpl.semRemoveEditText(android.widget.EditText)' on a null object reference
       at android.widget.EditText.onDetachedFromWindow(EditText.java:397)
       at android.view.View.dispatchDetachedFromWindow(View.java:22071)
       at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:6606)
       at android.view.ViewGroup.removeAllViews(ViewGroup.java:6552)
       at com.verygoodsecurity.vgscollect.view.InputFieldView.onDetachedFromWindow(InputFieldView.java:158)
       at android.view.View.dispatchDetachedFromWindow(View.java:22071)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4755)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4747)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6394)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6365)
       at android.view.ViewGroup.removeView(ViewGroup.java:6296)
```

**To Reproduce**
- No clear steps to reproduce. Happens after view with VGS editetext is deflated

**Expected behavior**
Should not crash

**Screenshots**
n/a

**Environment (please complete the following information):**
 - SDK Version [1.6.6]
 - Android Version: [11]
 - Device: [Galaxy Tab S6 Lite, Galaxy Tab S7, Galaxy Tab S7+, ]

**Additional context**
Seems to affecting only Galaxy tab models.
We have crashes also from VGS SDK versions prior to 1.6.6

**Possible Solution**
n/a

**Comment by Endorf** [comment]
Thank you for informing us about this issue.
We will have a look at this.

**Comment by Endorf** [comment]
Hi @mikkoville. Unfortunately, we still can’t reproduce this bug. Also, we mentioned that this bug is related only to Samsung-specific devices.
Do you use native VGS Collect for Android or with any frameworks, cross-platform frameworks?
Do you use our fields in Fragments? Could you please give more details if you are using Fragment in your flow?

Any additional information about realization would be appreciated.

**Comment by mikkoville** [comment]
HI @Endorf,
We have not been able to reproduce since we dont have access to those devices. This is crash report from our production through Crashlytics. To give some numbers e.g last 90 days this has crashed ~150 times affecting 85 users. They are all Samsung Tab models with Android 11.

> Do you use native VGS Collect for Android or with any frameworks, cross-platform frameworks?

We use native VGS collect in purely native Android app following your guidelines for integration

> Do you use our fields in Fragments? Could you please give more details if you are using Fragment in your flow?

We are not using fragments in VGS flow. We are using VGS components in a inflated View (inside Activity). Our logic is that after view is inflated we construct all VGS fields using `VGSCollect` and setup `addOnFieldStateChangeListener` and `addOnResponseListeners`. After views is deflated we call `VGSCollect#onDestroy()`
