### ISSUE TITLE
ConcurrentModificationException  from Debit Card Activation using CVV2

### ISSUE THREAD

**Issue by marcoRS** [verygoodsecurity/vgs-collect-android#425]
**Describe the bug**
Some of our user's are experiencing a crash that happens when they to activate a debit card by entering a CVV2 code. As soon as they enter the 2nd digit of a cvv2 code the crash seems to happen in a `com.verygoodsecurity.vgscollect.widget.CardVerificationCodeEditText`. 

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at kotlin.collections.CollectionsKt___CollectionsKt.forEach(CollectionsKt___CollectionsKt.java:1851)
       at com.verygoodsecurity.vgscollect.view.card.conection.BaseInputConnection.notifyAllListeners(BaseInputConnection.kt:57)
       at com.verygoodsecurity.vgscollect.view.card.conection.BaseInputConnection.run(BaseInputConnection.kt:33)
       at com.verygoodsecurity.vgscollect.view.internal.BaseInputField.updateTextChanged(BaseInputField.kt:177)
       at com.verygoodsecurity.vgscollect.view.internal.CVCInputField.updateTextChanged(CVCInputField.kt:90)
       at com.verygoodsecurity.vgscollect.view.internal.BaseInputField$setupInputConnectionListener$$inlined$addTextChangedListener$default$1.afterTextChanged(TextView.kt:98)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:10986)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:14117)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:314)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:506)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:304)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:849)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:199)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
       at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:169)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

This doesn't seem to happen to all users. One user in particular has the following device: **Galaxy s8 on Android 9**

**To Reproduce**
The user goes to our activation screen and starts to add their card info. As soon as they enter the 2nd cvv2 digit. The crash happens. 
**Expected behavior**
The app should not crash from a user inputting their cvv2 code. 

**Environment (please complete the following information):**
 - SDK Version 1.7.1
 - Android Version: 9
 - Device: Samsung Galaxy s8

**Possible Solution**
Unknown

**Comment by Endorf** [comment]
Thank you for informing us about this issue.
We will have a look at this.

**Comment by Endorf** [comment]
Hi @marcoRS. We released new stability release. Please check it out.

**Comment by marcoRS** [comment]
Thank you, we will update to this version 🙏🏽
