### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException in DigitInputFormatter

### ISSUE THREAD

**Issue by abaryzhikov** [verygoodsecurity/vgs-collect-android#650]
**Describe the bug**

The crash was introduced in VGS 1.8.4, here's the trace

```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (18 ... 18) ends beyond length 17
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:685)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
       at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:135)
       at android.text.Selection.setSelection(Selection.java:95)
       at android.text.Selection.setSelection(Selection.java:79)
       at android.text.Selection.setSelection(Selection.java:154)
       at com.verygoodsecurity.vgscollect.view.card.formatter.digit.DigitInputFormatter.afterTextChanged(DigitInputFormatter.kt:24)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:13037)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:16791)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1278)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:308)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:298)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)
       at android.widget.TextViewOnReceiveContentListener.replaceSelection(TextViewOnReceiveContentListener.java:123)
       at android.widget.TextViewOnReceiveContentListener.onReceiveContent(TextViewOnReceiveContentListener.java:105)
       at android.widget.TextView.onReceiveContent(TextView.java:16860)
       at android.view.View.performReceiveContent(View.java:9864)
       at android.widget.TextView.paste(TextView.java:15957)
       at android.widget.TextView.onTextContextMenuItem(TextView.java:15331)
       at android.widget.EditText.onTextContextMenuItem(EditText.java:252)
       at androidx.appcompat.widget.AppCompatEditText.onTextContextMenuItem(AppCompatEditText.java:367)
       at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:5592)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:3791)
       at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:160)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
       at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0(FloatingActionMode.java:128)
       at com.android.internal.view.FloatingActionMode.$r8$lambda$GLgk8deM4E5TWGJBQ3xBpWWp_5A()
       at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(:2)
       at com.android.internal.widget.floatingtoolbar.LocalFloatingToolbarPopup$2.onClick(LocalFloatingToolbarPopup.java:202)
       at android.view.View.performClick(View.java:8043)
       at android.view.View.performClickInternal(View.java:8020)
       at android.view.View.-$$Nest$mperformClickInternal()
       at android.view.View$PerformClick.run(View.java:31850)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**To Reproduce**
I tried to reproduce it on development and production builds, but couldn't trigger the crash.

**Environment (please complete the following information):**
 - SDK Version 1.9.0
 - Device: Galaxy S20 (Android 13), Galaxy A04 (Android 14)

**Comment by DmytroDm** [comment]
@abaryzhikov Hi, thank you for your information. The issue was fixed in v1.9.1, please try this version and let us know if the issue still occurs.
